package my.MrxSiN.gmailhideads.policy;

/** Generated by bfcc from brainfuck/constants.txt. Do not edit. */
final class BfAbi {

    private BfAbi() {
    }

    static final int ABI_MAJOR = 1;
    static final int ABI_MINOR = 0;
    static final int HEADER_SIZE = 8;
    static final int RESPONSE_BIT = 128;
    static final int PROG_ROW = 0;
    static final int PROG_SCOPE = 1;
    static final int ST_OK = 0;
    static final int ST_BAD_VERSION = 1;
    static final int ST_BAD_OPCODE = 2;
    static final int OP_AD_ROW = 16;
    static final int OP_SCOPE = 32;
    static final int V_NO = 0;
    static final int V_YES = 1;
    static final int NC_OTHER = 0;
    static final int NC_DOT = 1;
    static final int NC_C = 2;
    static final int NC_O = 3;
    static final int NC_M = 4;
    static final int NC_G = 5;
    static final int NC_L = 6;
    static final int NC_E = 7;
    static final int NC_A = 8;
    static final int NC_N = 9;
    static final int NC_D = 10;
    static final int NC_R = 11;
    static final int NC_I = 12;
    static final int NC_S = 13;
    static final int NC_T = 14;
    static final int NC_W = 15;
    static final int NC_UP_A = 16;
    static final int NC_UP_T = 17;
    static final int NC_UP_I = 18;
    static final int NC_UP_V = 19;
    static final int MAX_CHUNK = 255;
    static final int MAX_NAMES = 255;
    static final int RUNTIME_TAPE_MAX = 256;
    static final int RUNTIME_IN_CAP = 1048576;
    static final int RUNTIME_OUT_CAP = 1024;
    static final int BUDGET_BASE = 65536;
    static final int BUDGET_PER_BYTE = 64;
}
